default: &default
  adapter: postgresql
  host: <%= ENV['DB_HOST'] %>
  database: <%= ENV['DB_DATABASE'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: default_app_dev

test:
  <<: *default
  database: default_app_test

production:
  <<: *default
  database: default_app_prod