default: &default
  adapter: postgresql
  username: postgres
  password: password
  host: localhost
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: default_app_dev

test:
  <<: *default
  database: default_app_test

production:
  <<: *default
  database: default_app_prod